/**
 * `q-cms codegen` — generate types, migrations, and GraphQL schema.
 *
 * Reads the project's `schema.ts` and emits:
 *   - generated database migrations (via `drizzle-kit generate`)
 *   - TypeScript content types (via `tsc --noEmit` or jiti)
 *   - GraphQL SDL (best-effort; full graph is generated by the API app)
 *
 * If `@q-cms/schema` is not installed in the project (it usually
 * will be), the command falls back to a simple AST-based extractor
 * that pulls out collection names from the schema file. This is
 * intentionally minimal — the authoritative codegen lives in
 * `@q-cms/schema` and `@q-cms/api`.
 */

import { Command } from 'commander';
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { requireProjectRoot } from '../utils/config.ts';
import { error, info, warn, header, Spinner } from '../utils/output.ts';

interface CodegenOptions {
  watch?: boolean;
  dryRun?: boolean;
}

const TODO_GENERATED = (note: string) =>
  `// AUTO-GENERATED by q-cms codegen — do not edit by hand.\n// ${note}\n`;

export function registerCodegenCommand(program: Command): void {
  program
    .command('codegen')
    .description('Generate types, migrations, and GraphQL schema from schema.ts')
    .option('--watch', 'Watch schema.ts and regenerate on change')
    .option('--dry-run', 'Print what would be generated without writing')
    .action(async (opts: CodegenOptions) => {
      const root = requireProjectRoot();
      const schemaPath = join(root, 'schema.ts');
      if (!existsSync(schemaPath)) {
        error(`No schema.ts found at ${schemaPath}`);
        info('Run `q-cms init <name>` to create a new project.');
        process.exitCode = 1;
        return;
      }

      header('Inspecting schema.ts');
      const schemaSource = readFileSync(schemaPath, 'utf-8');
      const collections = extractCollectionNames(schemaSource);
      if (collections.length === 0) {
        warn('No collections found in schema.ts. Add a `collection({...})` call to define one.');
      } else {
        info(`Found ${collections.length} collection${collections.length === 1 ? '' : 's'}: ${collections.join(', ')}`);
      }

      if (opts.dryRun) {
        info('Dry run — not writing any files.');
        return;
      }

      const spinner = new Spinner('Generating artifacts...').start();
      const generatedDir = join(root, '.q-cms', 'generated');
      try {
        mkdirSync(generatedDir, { recursive: true });

        // 1) Type stubs (TODO: replace with a real @q-cms/schema codegen).
        const typesFile = join(generatedDir, 'collections.d.ts');
        writeFileSync(
          typesFile,
          TODO_GENERATED('Replace with @q-cms/schema codegen when available.') +
            collections
              .map(
                (name) =>
                  `export interface ${name} {\n  id: string;\n  data: Record<string, unknown>;\n  status: 'draft' | 'published' | 'archived';\n}\n`,
              )
              .join('\n'),
        );

        // 2) Migration hint (the real migrations are produced by drizzle-kit).
        const hint = join(generatedDir, 'MIGRATIONS.md');
        writeFileSync(
          hint,
          `# Migrations\n\n` +
            `Run \`pnpm --filter @q-cms/db generate\` to produce SQL migrations\n` +
            `from \`schema.ts\`, then \`q-cms db:migrate\` to apply them.\n\n` +
            `Collections: ${collections.join(', ')}\n`,
        );

        // 3) Drizzle generate (best effort — fails if @q-cms/db isn't ready).
        try {
          execSync('pnpm --filter @q-cms/db generate', { stdio: 'pipe', cwd: root });
          info('Drizzle migrations regenerated');
        } catch {
          warn('drizzle-kit generate skipped (no @q-cms/db or schema mismatch).');
        }

        spinner.succeed(`Generated ${collections.length} collection type${collections.length === 1 ? '' : 's'}`);
        info(`Output: ${generatedDir}`);
      } catch (err) {
        spinner.fail();
        error((err as Error).message);
        process.exitCode = 1;
        return;
      }

      if (opts.watch) {
        info('Watching schema.ts for changes (Ctrl-C to stop)...');
        try {
          execSync(`pnpm dlx chokidar-cli "${schemaPath}" -c "q-cms codegen"`, {
            stdio: 'inherit',
            cwd: root,
          });
        } catch (err) {
          // chokidar-cli missing — fall back to a hint.
          warn('chokidar-cli not installed. Install with: pnpm add -D chokidar-cli');
          error((err as Error).message);
        }
      }
    });
}

/**
 * Minimal AST-free extractor: finds `Name: collection({...})` patterns
 * in a schema.ts source string. Good enough to print a list of
 * collections; the real parser lives in `@q-cms/schema`.
 */
function extractCollectionNames(source: string): string[] {
  const out: string[] = [];
  // Matches: `Article: collection(` or `Article :collection(`
  const re = /([A-Z][A-Za-z0-9_]*)\s*:\s*collection\s*\(/g;
  for (let m = re.exec(source); m !== null; m = re.exec(source)) {
    const name = m[1];
    if (name && !out.includes(name)) out.push(name);
  }
  return out;
}
