/**
 * Integration tests for repositories.
 *
 * Uses Testcontainers to spin up a real PostgreSQL 16 instance, applies
 * the schema (via `drizzle-kit push` semantics — executed against the
 * ephemeral DB), and exercises User CRUD, Entry create+list+publish, and
 * the unique constraint on `users.email`.
 *
 * Marked with `.skip` by default to keep the default `pnpm test` loop
 * fast; run via:
 * ```sh
 * pnpm test:integration
 * ```
 *
 * If Testcontainers / Docker is unavailable, the suite silently exits.
 */

import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import postgres from 'postgres';

import * as schema from '../src/schema/index.ts';
import { UserRepository } from '../src/repositories/user-repository.ts';
import { EntryRepository } from '../src/repositories/entry-repository.ts';
import { AuditLogRepository } from '../src/repositories/audit-log-repository.ts';

let container: StartedPostgreSqlContainer | undefined;
let sqlClient: ReturnType<typeof postgres> | undefined;
let db: ReturnType<typeof drizzle<typeof schema>> | undefined;

const skip = (() => {
  if (process.env['SKIP_INTEGRATION'] === '1') return true;
  return false;
})();

beforeAll(async () => {
  if (skip) return;
  try {
    container = await new PostgreSqlContainer('postgres:16-alpine')
      .withDatabase('qcms_test')
      .withUsername('qcms')
      .withPassword('qcms')
      .start();
  } catch (cause) {
    console.warn('[integration] Docker not available — skipping tests:', cause);
    return;
  }

  const url = container.getConnectionUri();
  sqlClient = postgres(url, { max: 4, prepare: false });
  db = drizzle(sqlClient, { schema });

  // Apply schema via raw DDL. We push the Drizzle schema in-process by
  // executing the DDL strings — `drizzle-kit push` requires a long-lived
  // CLI; this in-test approach is more robust.
  await applySchema(sqlClient);
}, 120_000);

afterAll(async () => {
  if (sqlClient) await sqlClient.end({ timeout: 5 });
  if (container) await container.stop();
}, 60_000);

async function applySchema(client: ReturnType<typeof postgres>): Promise<void> {
  // Minimal DDL — just enough to exercise the repositories. The full
  // migration is generated by `drizzle-kit`.
  await client.unsafe(`
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";
    CREATE EXTENSION IF NOT EXISTS "citext";

    CREATE TABLE IF NOT EXISTS users (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      email CITEXT UNIQUE NOT NULL,
      username TEXT UNIQUE,
      password_hash TEXT,
      first_name TEXT,
      last_name TEXT,
      avatar_id UUID,
      is_active BOOLEAN NOT NULL DEFAULT true,
      is_super_admin BOOLEAN NOT NULL DEFAULT false,
      totp_secret TEXT,
      totp_enabled BOOLEAN NOT NULL DEFAULT false,
      email_verified_at TIMESTAMPTZ,
      last_login_at TIMESTAMPTZ,
      metadata JSONB NOT NULL DEFAULT '{}',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS sessions (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token_hash TEXT NOT NULL UNIQUE,
      ip INET,
      user_agent TEXT,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      revoked_at TIMESTAMPTZ
    );

    CREATE TABLE IF NOT EXISTS api_tokens (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,
      prefix TEXT NOT NULL,
      scopes TEXT NOT NULL DEFAULT '{}',
      expires_at TIMESTAMPTZ,
      last_used_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      revoked_at TIMESTAMPTZ
    );

    CREATE TABLE IF NOT EXISTS collections (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      name TEXT UNIQUE NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      is_singleton TEXT NOT NULL DEFAULT 'false',
      draft_and_publish TEXT NOT NULL DEFAULT 'true',
      versioning TEXT NOT NULL DEFAULT 'true',
      schema JSONB NOT NULL,
      settings JSONB NOT NULL DEFAULT '{}',
      display_name TEXT NOT NULL,
      display_name_i18n JSONB NOT NULL DEFAULT '{}',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS entries (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      collection_id UUID NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
      slug TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      locale TEXT NOT NULL,
      is_default_locale TEXT NOT NULL DEFAULT 'false',
      data JSONB NOT NULL DEFAULT '{}',
      title TEXT,
      search_vector TSVECTOR,
      published_at TIMESTAMPTZ,
      scheduled_publish_at TIMESTAMPTZ,
      scheduled_unpublish_at TIMESTAMPTZ,
      created_by UUID,
      updated_by UUID,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS audit_log (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      actor_id UUID,
      actor_email TEXT,
      action TEXT NOT NULL,
      resource_type TEXT NOT NULL,
      resource_id TEXT,
      diff JSONB,
      context JSONB NOT NULL DEFAULT '{}',
      occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
}

describe.skipIf(skip)('repositories (integration)', () => {
  it('creates, reads, and deletes a user', async () => {
    if (!db) return;
    const users = new UserRepository(db);
    const created = await users.create({ email: 'alice@example.com', firstName: 'Alice' });
    expect(created.email).toBe('alice@example.com');

    const found = await users.findById(created.id);
    expect(found.ok).toBe(true);
    if (found.ok) expect(found.value.id).toBe(created.id);

    const byEmail = await users.findByEmail('alice@example.com');
    expect(byEmail.ok).toBe(true);

    await users.delete(created.id);
    const gone = await users.findById(created.id);
    expect(gone.ok).toBe(false);
  });

  it('rejects duplicate e-mails via unique constraint', async () => {
    if (!db) return;
    const users = new UserRepository(db);
    await users.create({ email: 'bob@example.com' });
    await expect(users.create({ email: 'bob@example.com' })).rejects.toThrow(/unique|conflict/i);
  });

  it('creates, lists, and publishes an entry', async () => {
    if (!db) return;
    const entries = new EntryRepository(db);
    const audit = new AuditLogRepository(db);

    // Create a collection first.
    const [col] = await db
      .insert(schema.collections)
      .values({
        name: `Articles-${Date.now()}`,
        slug: `articles-${Date.now()}`,
        schema: { type: 'object' },
        displayName: 'Article',
      })
      .returning();
    expect(col).toBeDefined();

    if (!col) throw new Error('collection insert failed');
    const collectionId = col.id as unknown as ReturnType<typeof schema.collectionId>;

    const created = await entries.create({
      collectionId,
      locale: 'en',
      data: { title: 'Hello, world!', excerpt: 'greeting' },
    });
    expect(created.status).toBe('draft');
    expect(created.data['title']).toBe('Hello, world!');

    const list = await entries.list({ collectionId, status: 'draft' });
    expect(list.data.length).toBeGreaterThan(0);

    const published = await entries.publish(created.id);
    expect(published.status).toBe('published');
    expect(published.publishedAt).not.toBeNull();

    await audit.record({
      action: 'entry.publish',
      resourceType: 'entry',
      resourceId: created.id,
    });

    const log = await audit.query({ action: 'entry.publish' });
    expect(log.data.length).toBeGreaterThan(0);
  });
});

describe('Result utilities (unit)', () => {
  it('Ok / Err helpers compose', async () => {
    const { Ok, Err, map, andThen, fromPromise } = await import('@q-cms/core/result');
    const ok = Ok(2);
    const doubled = map(ok, (n) => n * 2);
    expect(doubled.ok).toBe(true);
    if (doubled.ok) expect(doubled.value).toBe(4);

    const chained = andThen(Ok(3), (n) => (n > 0 ? Ok(n + 1) : Err(new Error('nope'))));
    expect(chained.ok).toBe(true);

    const caught = await fromPromise(Promise.reject(new Error('boom')));
    expect(caught.ok).toBe(false);

    const ok2 = await fromPromise(Promise.resolve(7));
    expect(ok2.ok).toBe(true);
    if (ok2.ok) expect(ok2.value).toBe(7);

    // Reference unused to satisfy noUnusedLocals in strict mode.
    void sql;
  });
});
